
platform :ios, '9.0'

target 'FirstSwiftDemo' do
  use_frameworks!
  inhibit_all_warnings!
  pod 'SDWebImage', :git => 'https://gitee.com/mail2chensh/SDWebImage.git'
  pod 'SnapKit', :git => 'https://gitee.com/Cocoapods-Wand/SnapKit.git'
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON', :git => 'https://gitee.com/mirrors/SwiftyJSON.git'
  pod 'HandyJSON', :git => 'https://gitee.com/teenloong/HandyJSON.git'

end

